### ISSUE TITLE
DeployMan for Android 64bit

### ISSUE THREAD

**Issue by gliden** [grijjy/DelphiSocialFrameworks#5]
Is there a new Version of DeployMan for Android 64bit?
Currently the files were only saved for 32bit.

**Comment by grijjy** [comment]
We updated the DeployMan for Android 64bit,
https://github.com/grijjy/DelphiSocialFrameworks/tree/master/DeployMan
*Use at your own risk and always backup your project*

**Comment by gliden** [comment]
Thank you very much 👍
