### ISSUE TITLE
Make DeployMan tool open source

### ISSUE THREAD

**Issue by viniciusfbb** [grijjy/DelphiSocialFrameworks#8]
I would like to thank you for the tutorials and the free tools, one of which I use daily, DeployMan. It would be interesting if you made the source available because sometimes there are problems that we could solve them by running DeployMan in debug mode and studying the source. We could even contribute to improving it.

**Comment by Zeus64** [comment]
yes I agree too :)

**Comment by Martifan** [comment]
hello, but I constantly get an error:
Access violation at address 006E81CB in module 'DeployMan.exe' Read of address 00000008
who knows why?

**Comment by allendrennan** [comment]
We are planning to do this.

**Comment by Zeus64** [comment]
thanks Allen !

**Comment by allendrennan** [comment]
Should be live now, https://github.com/grijjy/GrijjyDeployMan

**Comment by erikvanbilsen** [comment]
Just pushed version 1.1, along with a new executable on the Releases page.
